sudo: required

services:
  - docker

language: elixir
elixir:
  - 1.4.2

before_install:
  - docker build -t arsduo/load_resource .
  - docker ps -a
  - docker run arsduo/load_resource /bin/sh -c "mix test"

script:
  - mix test