sudo: required

services:
  - postgresql

language: elixir
elixir:
  - 1.4.2

before_install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  - mix ecto.create
  - mix ecto.migrate

script:
  - mix test